import BiologyEcology from './BiologyEcology/src/index.vue'
import MathProbability from './MathProbability/src/index.vue'
import PhysicsAstronomy from './PhysicsAstronomy/src/index.vue'
import EnglishSyntax from './EnglishSyntax/src/index.vue'
import ChasingProblem from './ChasingProblem/src/index.vue'
import NewtonSecondLaw from './NewtonSecondLaw/src/index.vue'
import BiologyEvolution from './BiologyEvolution/src/index.vue'
import ChemistryEquilibrium from './ChemistryEquilibrium/src/index.vue'
import ChemistrySynthesis from './ChemistrySynthesis/src/index.vue'
import ChinaParovince from './ChinaParovince/src/index.vue'
import ChineseAntonyms from './ChineseAntonyms/src/index.vue'
import ChineseRadicalsWords from './ChineseRadicalsWords/src/index.vue'
import ChineseSynonyms from './ChineseSynonyms/src/index.vue'
import EnglishGrammar from './EnglishGrammar/src/index.vue'
import EnglishOrderSentences from './EnglishOrderSentences/src/index.vue'
import HistoryDynasty from './HistoryDynasty/src/index.vue'
import MathFunction from './MathFunction/src/index.vue'
import MicroChemical from './MicroChemical/src/index.vue'
import PeriodicTable from './PeriodicTable/src/index.vue'
import PhysicsLever from './PhysicsLever/src/index.vue'
import RefractionDemo from './Refraction/src/index.vue'
import WordOrdering from './WordOrdering/src/index.vue'


export default { BiologyEcology, MathProbability, PhysicsAstronomy, EnglishSyntax, ChasingProblem, NewtonSecondLaw, BiologyEvolution, ChemistryEquilibrium, ChemistrySynthesis, ChinaParovince, ChineseAntonyms, ChineseRadicalsWords, ChineseSynonyms, EnglishGrammar, EnglishOrderSentences, HistoryDynasty, MathFunction, MicroChemical, PeriodicTable, PhysicsLever, RefractionDemo, WordOrdering }